/**
 * Curated DC neighborhoods + metro/city seeds for dropdowns and filters (GAT-5).
 * Nominatim still augments results when users type.
 */

export const NEIGHBORHOOD_AND_CITY_SEEDS = [
  // Washington, D.C. neighborhoods
  "Adams Morgan, Washington, DC",
  "American University Park, Washington, DC",
  "Anacostia, Washington, DC",
  "Bloomingdale, Washington, DC",
  "Brightwood, Washington, DC",
  "Brookland, Washington, DC",
  "Burleith, Washington, DC",
  "Capitol Hill, Washington, DC",
  "Cathedral Heights, Washington, DC",
  "Chevy Chase, Washington, DC",
  "Chinatown, Washington, DC",
  "Cleveland Park, Washington, DC",
  "Columbia Heights, Washington, DC",
  "Congress Heights, Washington, DC",
  "Deanwood, Washington, DC",
  "Downtown, Washington, DC",
  "Dupont Circle, Washington, DC",
  "Eckington, Washington, DC",
  "Edgewood, Washington, DC",
  "Foggy Bottom, Washington, DC",
  "Fort Totten, Washington, DC",
  "Foxhall, Washington, DC",
  "Friendship Heights, Washington, DC",
  "Georgetown, Washington, DC",
  "Glover Park, Washington, DC",
  "H Street Corridor, Washington, DC",
  "Kalorama Triangle, Washington, DC",
  "Lanier Heights, Washington, DC",
  "LeDroit Park, Washington, DC",
  "Logan Circle, Washington, DC",
  "Meridian Hill, Washington, DC",
  "Mount Pleasant, Washington, DC",
  "Mount Vernon Square, Washington, DC",
  "Navy Yard, Washington, DC",
  "NoMa, Washington, DC",
  "Palisades, Washington, DC",
  "Park View, Washington, DC",
  "Penn Quarter, Washington, DC",
  "Petworth, Washington, DC",
  "Pleasant Plains, Washington, DC",
  "Shaw, Washington, DC",
  "Sheridan-Kalorama, Washington, DC",
  "Southwest Waterfront / The Wharf, Washington, DC",
  "Spring Valley, Washington, DC",
  "Takoma, Washington, DC",
  "Tenleytown, Washington, DC",
  "Trinidad, Washington, DC",
  "U Street Corridor, Washington, DC",
  "West End, Washington, DC",
  "Woodley Park, Washington, DC",
  // NYC neighborhoods
  "East Village, Manhattan",
  "West Village, Manhattan",
  "SoHo, Manhattan",
  "Tribeca, Manhattan",
  "Upper West Side, Manhattan",
  "Upper East Side, Manhattan",
  "Harlem, Manhattan",
  "Williamsburg, Brooklyn",
  "Bushwick, Brooklyn",
  "Park Slope, Brooklyn",
  "Bed-Stuy, Brooklyn",
  "Greenpoint, Brooklyn",
  "Astoria, Queens",
  // US cities (expanded)
  "Boston, MA",
  "Cambridge, MA",
  "New York, NY",
  "Brooklyn, NY",
  "San Francisco, CA",
  "Oakland, CA",
  "Berkeley, CA",
  "Los Angeles, CA",
  "Santa Monica, CA",
  "San Diego, CA",
  "San Jose, CA",
  "Sacramento, CA",
  "Fresno, CA",
  "Chicago, IL",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "San Antonio, TX",
  "Fort Worth, TX",
  "Seattle, WA",
  "Tacoma, WA",
  "Spokane, WA",
  "Portland, OR",
  "Denver, CO",
  "Boulder, CO",
  "Colorado Springs, CO",
  "Washington, DC",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Miami, FL",
  "Tampa, FL",
  "Orlando, FL",
  "Jacksonville, FL",
  "Atlanta, GA",
  "Savannah, GA",
  "Charleston, SC",
  "Nashville, TN",
  "Knoxville, TN",
  "Memphis, TN",
  "Minneapolis, MN",
  "Saint Paul, MN",
  "Detroit, MI",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Indianapolis, IN",
  "Kansas City, MO",
  "St. Louis, MO",
  "Milwaukee, WI",
  "Madison, WI",
  "New Orleans, LA",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Las Vegas, NV",
  "Reno, NV",
  "Salt Lake City, UT",
  "Provo, UT",
  "Albuquerque, NM",
  "Boise, ID",
  "Omaha, NE",
  "Des Moines, IA",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Little Rock, AR",
  "Birmingham, AL",
  "Huntsville, AL",
  "Mobile, AL",
  "Jackson, MS",
  "Louisville, KY",
  "Lexington, KY",
  "Charlotte, NC",
  "Raleigh, NC",
  "Durham, NC",
  "Wilmington, NC",
  "Greenville, SC",
  "Baltimore, MD",
  "Bethesda, MD",
  "Silver Spring, MD",
  "Annapolis, MD",
  "Arlington, VA",
  "Alexandria, VA",
  "Richmond, VA",
  "Norfolk, VA",
  "Charlottesville, VA",
  "Burlington, VT",
  "Portland, ME",
  "Providence, RI",
  "Hartford, CT",
  "Buffalo, NY",
  "Rochester, NY",
  "Albany, NY",
  "Anchorage, AK",
  "Honolulu, HI",
  // International
  "Toronto, ON",
  "Vancouver, BC",
  "Montreal, QC",
  "London, UK",
  "Paris, FR",
  "Berlin, DE",
  "Amsterdam, NL",
  "Lisbon, PT",
  "Madrid, ES",
  "Barcelona, ES",
  "Mexico City, MX",
  "Tokyo, JP",
  "Seoul, KR",
  "Singapore",
  "Sydney, AU",
] as const;
