/**
 * Curated DC neighborhoods + metro/city seeds for dropdowns and filters (GAT-5).
 * Nominatim still augments results when users type.
 */

/** Canonical DC neighborhoods (shown first when the field is empty). */
export const DC_NEIGHBORHOOD_SEEDS = [
  "Adams Morgan, Washington, DC",
  "American University Park, Washington, DC",
  "Anacostia, Washington, DC",
  "Bloomingdale, Washington, DC",
  "Brightwood, Washington, DC",
  "Brightwood Park, Washington, DC",
  "Brookland, Washington, DC",
  "Burleith, Washington, DC",
  "Capitol Hill, Washington, DC",
  "Cathedral Heights, Washington, DC",
  "Chevy Chase, Washington, DC",
  "Chinatown, Washington, DC",
  "Cleveland Park, Washington, DC",
  "Columbia Heights, Washington, DC",
  "Congress Heights, Washington, DC",
  "Deanwood, Washington, DC",
  "Downtown, Washington, DC",
  "Dupont Circle, Washington, DC",
  "Eckington, Washington, DC",
  "Edgewood, Washington, DC",
  "Foggy Bottom, Washington, DC",
  "Fort Totten, Washington, DC",
  "Foxhall, Washington, DC",
  "Friendship Heights, Washington, DC",
  "Georgetown, Washington, DC",
  "Glover Park, Washington, DC",
  "H Street Corridor, Washington, DC",
  "Kalorama Triangle, Washington, DC",
  "Lanier Heights, Washington, DC",
  "LeDroit Park, Washington, DC",
  "Logan Circle, Washington, DC",
  "Meridian Hill, Washington, DC",
  "Mount Pleasant, Washington, DC",
  "Mount Vernon Square, Washington, DC",
  "Navy Yard, Washington, DC",
  "NoMa, Washington, DC",
  "Palisades, Washington, DC",
  "Park View, Washington, DC",
  "Penn Quarter, Washington, DC",
  "Petworth, Washington, DC",
  "Pleasant Plains, Washington, DC",
  "Shaw, Washington, DC",
  "Sheridan-Kalorama, Washington, DC",
  "Southwest Waterfront / The Wharf, Washington, DC",
  "Spring Valley, Washington, DC",
  "Takoma, Washington, DC",
  "Tenleytown, Washington, DC",
  "Trinidad, Washington, DC",
  "U Street Corridor, Washington, DC",
  "West End, Washington, DC",
  "Woodley Park, Washington, DC",
] as const;

/** Additional DC-adjacent / lesser-used wards (still in DC). */
const DC_EXTENDED_SEEDS = [
  "Ivy City, Washington, DC",
  "Riggs Park, Washington, DC",
  "Manor Park, Washington, DC",
  "Potomac Yard, Washington, DC",
  "McLean Gardens, Washington, DC",
  "Barnaby Woods, Washington, DC",
] as const;

const NYC_NEIGHBORHOOD_SEEDS = [
  "East Village, Manhattan",
  "West Village, Manhattan",
  "SoHo, Manhattan",
  "Tribeca, Manhattan",
  "Upper West Side, Manhattan",
  "Upper East Side, Manhattan",
  "Harlem, Manhattan",
  "Williamsburg, Brooklyn",
  "Bushwick, Brooklyn",
  "Park Slope, Brooklyn",
  "Bed-Stuy, Brooklyn",
  "Greenpoint, Brooklyn",
  "Astoria, Queens",
  "Long Island City, Queens",
] as const;

const US_METRO_SEEDS = [
  "Boston, MA",
  "Cambridge, MA",
  "New Haven, CT",
  "Hartford, CT",
  "Providence, RI",
  "Buffalo, NY",
  "Rochester, NY",
  "Albany, NY",
  "New York, NY",
  "Brooklyn, NY",
  "Jersey City, NJ",
  "Newark, NJ",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Washington, DC",
  "Baltimore, MD",
  "Bethesda, MD",
  "Silver Spring, MD",
  "Annapolis, MD",
  "Arlington, VA",
  "Alexandria, VA",
  "Fairfax, VA",
  "Reston, VA",
  "Richmond, VA",
  "Norfolk, VA",
  "Charlottesville, VA",
  "Raleigh, NC",
  "Durham, NC",
  "Charlotte, NC",
  "Wilmington, NC",
  "Charleston, SC",
  "Greenville, SC",
  "Atlanta, GA",
  "Savannah, GA",
  "Miami, FL",
  "Tampa, FL",
  "Orlando, FL",
  "Jacksonville, FL",
  "St. Petersburg, FL",
  "Sarasota, FL",
  "Nashville, TN",
  "Knoxville, TN",
  "Memphis, TN",
  "Chicago, IL",
  "Minneapolis, MN",
  "Saint Paul, MN",
  "Detroit, MI",
  "Columbus, OH",
  "Cleveland, OH",
  "Cincinnati, OH",
  "Indianapolis, IN",
  "Kansas City, MO",
  "St. Louis, MO",
  "Milwaukee, WI",
  "Madison, WI",
  "New Orleans, LA",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "San Antonio, TX",
  "Fort Worth, TX",
  "Denver, CO",
  "Boulder, CO",
  "Colorado Springs, CO",
  "Phoenix, AZ",
  "Tucson, AZ",
  "Scottsdale, AZ",
  "Tempe, AZ",
  "Las Vegas, NV",
  "Reno, NV",
  "Salt Lake City, UT",
  "Provo, UT",
  "Seattle, WA",
  "Tacoma, WA",
  "Spokane, WA",
  "Portland, OR",
  "San Francisco, CA",
  "Oakland, CA",
  "Berkeley, CA",
  "San Jose, CA",
  "Sacramento, CA",
  "Fresno, CA",
  "Los Angeles, CA",
  "Long Beach, CA",
  "Santa Monica, CA",
  "San Diego, CA",
  "Albuquerque, NM",
  "Boise, ID",
  "Omaha, NE",
  "Des Moines, IA",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Little Rock, AR",
  "Birmingham, AL",
  "Huntsville, AL",
  "Mobile, AL",
  "Jackson, MS",
  "Louisville, KY",
  "Lexington, KY",
  "Wichita, KS",
  "Anchorage, AK",
  "Honolulu, HI",
  "Burlington, VT",
  "Portland, ME",
  "Stamford, CT",
] as const;

const INTERNATIONAL_SEEDS = [
  "Toronto, ON",
  "Vancouver, BC",
  "Montreal, QC",
  "London, UK",
  "Paris, FR",
  "Berlin, DE",
  "Amsterdam, NL",
  "Lisbon, PT",
  "Madrid, ES",
  "Barcelona, ES",
  "Mexico City, MX",
  "Tokyo, JP",
  "Seoul, KR",
  "Singapore",
  "Sydney, AU",
] as const;

/** Full merged list for filters / static exports (deduped). */
export const NEIGHBORHOOD_AND_CITY_SEEDS = Array.from(
  new Set<string>([
    ...DC_NEIGHBORHOOD_SEEDS,
    ...DC_EXTENDED_SEEDS,
    ...NYC_NEIGHBORHOOD_SEEDS,
    ...US_METRO_SEEDS,
    ...INTERNATIONAL_SEEDS,
  ]),
).sort((a, b) => a.localeCompare(b));
